# Generated by Django 3.1.6 on 2021-02-20 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210216_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(related_name='_account_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
