# Generated by Django 3.1.2 on 2020-10-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updat',
        ),
    ]
