# Generated by Django 3.1.2 on 2020-10-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201014_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updat',
            new_name='update',
        ),
    ]
