# Generated by Django 3.1.8 on 2021-05-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0002_votenotification_voted_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenotification',
            name='voted_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted post+', to='blog.post'),
        ),
    ]
