# Generated by Django 3.1.8 on 2021-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210514_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
