# Generated by Django 3.1.8 on 2021-05-14 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210514_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follownotification',
            name='touser',
        ),
        migrations.RemoveField(
            model_name='votenotification',
            name='touser',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications+', to='users.user'),
            preserve_default=False,
        ),
    ]
