# Generated by Django 3.1.8 on 2021-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210514_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='follownotification',
            name='message',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votenotification',
            name='message',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
