# Generated by Django 3.1.8 on 2021-05-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210515_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follownotification',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='votenotification',
            name='updated',
        ),
    ]
